name: build
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash ordenar.sh
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: 8.12
      - run: gradle build
      - run: bash renombrar.sh
      - uses: actions/upload-artifact@v4
        with:
          name: TotemAstraeusv2
          path: out/TotemAstraeusv2.jar
